### ISSUE TITLE
Unsolicited spam on my commit email

### ISSUE THREAD

**Issue by Exagone313** [tiyaro/stable-diffusion-api#1]
Hello,

You are using my commit email to send spam linking to your project. Even the "unsubscribe" link points to your website and is fake.

Remove me from your mailing list or I will take actions. This is a clear GDPR violation as I'm a European citizen.

Thank you.

**Comment by Venkat2811** [comment]
Hello @Exagone313 ,

Thank you for reaching out.  My apologies, there was a bug in template which resulted in `unsubscribe` link pointing to our blog.

As per your request, you are removed from mailing list and unsubscribed.
